#!/usr/bin/env bash

set -e

if [[ $1 == "commit" ]]; then
  COMMIT_URL=$(git config --local --default "" remote.origin.commitUrl | sed "s/\/\{0,1\}$//")
  if [[ ! -n ${COMMIT_URL} ]]; then
    echo "Git config remote.origin.commitUrl is required but it isn't set"
    echo "e.g.: git config --local remote.origin.commitUrl \"https://github.com/jmera/bin/commit/\""
    exit 1
  fi

  COMMIT=${2-$(git rev-parse HEAD)}

  open "$COMMIT_URL/$COMMIT"
elif [[ $1 == "tree" ]]; then
  TREE_URL=$(git config --local --default "" remote.origin.treeUrl | sed "s/\/\{0,1\}$//")
  if [[ ! -n ${TREE_URL} ]]; then
    echo "Git config remote.origin.treeUrl is required but it isn't set"
    echo "e.g.: git config --local remote.origin.treeUrl \"https://github.com/jmera/bin/tree/\""
    exit 1
  fi

  COMMIT=${2-$(git rev-parse HEAD)}

  open "$TREE_URL/$COMMIT"
fi
